name: TVB Downloads Post-Processing
on:
  # schedule:
  #   - cron: '0 2 * * *' 
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (no actual file moves)'
        required: true
        type: boolean
        default: false

jobs:
  Organize:
    runs-on: arc-calvinz360-home-labs
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          enable-cache: false
      
      - name: Execute script
        run: uv run scripts/tvb_postprocess.py
        env:
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}