name: TVB Downloads Post-Processing
on:
  # schedule:
  #   - cron: '0 2 * * *' 
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (no actual file moves)'
        required: true
        type: boolean
        default: false

jobs:
  Organize:
    runs-on: arc-calvinz360-home-labs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.14.x
      
      - name: Execute script
        run: python scripts/tvb_postprocess.py
        env:
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}